### ISSUE TITLE
[FEATURE] Allow docker to push logs to Cloudwatch

### ISSUE THREAD

**Issue by bshien** [opensearch-project/opensearch-metrics#47]
### Is your feature request related to a problem?

The nginx proxy holds a docker container to sign requests so users can authenticate with OpenSearch Dashboards. When users access the dashboard, docker will start creating logs, which could cause an outage if the EC2 fills up with docker logs.

### What solution would you like?

We would like to push the docker logs to a Cloudwatch log group.

**Comment by prudhvigodithi** [comment]
@bshien can we close this issue?
