### ISSUE TITLE
[FEATURE] Add Timeseries graph of failing test classes for Dashboard - Gradle Check

### ISSUE THREAD

**Issue by kiranprakash154** [opensearch-project/opensearch-metrics#52]
### Is your feature request related to a problem?
With the existing dashboard I cannot see the performance of test over time, i.e if a test failure has been decreasing / increasing over time, this will be particularly helpful after fixing a flaky test and seeing the impact of the fix over time. 

### What solution would you like?
In addition to the pie chart (Gradle Check - Test class failures top 50 hitters) a time series based graph would be immensely valuable

### What alternatives have you considered?
Generating a graph from the Explore metrics section.

**Comment by prudhvigodithi** [comment]
[Triage]
@bshien can you please take care of this?
@getsaurabh02

**Comment by bshien** [comment]
Hi @kiranprakash154 , 

The visualization already exists, look for the second to last graph named "Gradle Check - (TSVB) Top test class failures". If you want to see for a particular test class how it has changed over time, you can add the filter at the top "test_class": "<name of the test class>".

**Comment by bshien** [comment]
Here is a screenshot for your reference:

<img width="1706" alt="Screenshot 2024-08-28 at 9 39 51 AM" src="https://github.com/user-attachments/assets/c5ec00c8-90fa-4118-b271-e43a14961cb8">
