### ISSUE TITLE
[BUG] Missing license header

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-metrics#55]
### What is the bug?
Many files in this repo are missing license headers

### How can one reproduce the bug?
Go through https://github.com/opensearch-project/opensearch-metrics/tree/main/src

### What is the expected behavior?
All files should have license headers. Also as an enhancement, add license checker similar to https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/license-header-checker.yml

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by prudhvigodithi** [comment]
[Triage]
Thanks for the PR https://github.com/opensearch-project/opensearch-metrics/pull/54 @gaiksaya 
@getsaurabh02 @bshien

**Comment by prudhvigodithi** [comment]
@gaiksaya can we close this issue?

**Comment by gaiksaya** [comment]
> @gaiksaya can we close this issue?

I dont think so. I just added for infrastructure code but java code still needs license headers. Regarding license checker I think that can be tracked in separate issue.
