### ISSUE TITLE
Visualization to link GitHub owner alias which can be used by the release manager

### ISSUE THREAD

**Issue by bshien** [opensearch-project/opensearch-metrics#59]
### Is your feature request related to a problem?
A data table visualization to map the GitHub alias assigned to the release issues. Should be able to filter per release.

### What solution would you like?
A dashboard that shows a mapping of github alias that would allow release managers to easily find out who to ping.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by prudhvigodithi** [comment]
Today for the [Release Metrics Dashboard](https://metrics.opensearch.org/_dashboards/app/dashboards?security_tenant=global#/view/12d47dd0-e0cc-11ee-86f3-3358a59f8c46?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Release%20Metrics',viewMode:view)) there are mechanisms added to make sure the release owners (the component level release issue assignees) are pulled and displayed, flagging the repos with no release owners.

![image](https://github.com/user-attachments/assets/141a2e9d-02e1-4eb6-9aab-f17fecc1b774)

![image](https://github.com/user-attachments/assets/4c13c5e6-1cf7-4f33-b30d-ba8a3f6335fc)

**Comment by prudhvigodithi** [comment]
Closing this issue as the github user alias, the component release owner visualization is now in https://opensearch.org/release-dashboard.
Thank you
