### ISSUE TITLE
[Operations] How to better visualize OpenSearch-Project status?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-metrics#65]
### Is your feature request related to a problem? Please describe

During the weekly operations meeting, there has been an ongoing question- how do we know if we are on track or not?  Using release issues is focused on individual releases and there can be as many as 3 active release actions happening at once.  Getting a good 'feel' for the project health doesn't have strong mechanisms

### Describe the solution you'd like

There should be a place where the OpenSearch project can visualize projects and critical metrics about them.  Number of stale issues/PRs.  How many issues are untriaged.  How many outstanding release specific issues are still unresolved.

Additional health metrics could include community engagement, incoming issue rate, or time since last release.

**Comment by prudhvigodithi** [comment]
[Triage]
Hey @peternied we have lot of data about the OpenSearch-Project in the metrics dashboard, it should cover majority of the points you mentioned. The repo [README](https://github.com/opensearch-project/opensearch-metrics/blob/main/README.md) shows the list of available status metrics, Please check the [OpenSearch Project Insights](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/a987a4b0-d801-11ee-8a84-e3710560950c), [OpenSearch Ops Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/f1ad21c0-e323-11ee-9a74-07cd3b4ff414) dashboards for more details.

Thank you 
@getsaurabh02 @dblock

**Comment by prudhvigodithi** [comment]
Closing this issue, feel-free to re-open or create a new one for new metric (to better visualize the OpenSearch Project status) if required.
Thanks
