### ISSUE TITLE
[FEATURE] Central View of the Release Metrics Dashboards

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-metrics#69]
### Is your feature request related to a problem?
As part of https://github.com/opensearch-project/opensearch-metrics/issues/51 today we have multiple dashboards for release metrics. These dashboards include metrics that can be used by the release manager to drive the release, metrics for the community to track the current status of the release and metrics for the component level release owners and teams to track the build and integration test failures.

Dashboards for release manager and community to track the release: [Dashboard Link](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/12d47dd0-e0cc-11ee-86f3-3358a59f8c46).

Dashboards for Build and Integration Test failures: [Dashboards Link](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa).

### What solution would you like?
Have a central view of all the release dashboards that are related to release. Having a central view will eliminate multiple clicks of moving around between dashboards and a user can have a central view for the release metrics.

Combining all release-related visualizations into a single dashboard is not a viable solution. Applying global filters at the dashboard level would affect all visualizations within it, which becomes problematic given the extensive data and multiple metrics involved. The data is organized into multiple indices, each with different key-value mappings. Since no two metric categories for releases are identical, consolidating them under a single dashboard is not a solution.

Example:
The Dashboards for Build and Integration Test failures: [Dashboards Link](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa) has data about the integration test failures for an Release candidate, the filter applied for these Dashboard are related to build_number, platform, distribution, rc_number etc, whereas for Dashboards for release manager and community to track the release: [Dashboard Link](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/12d47dd0-e0cc-11ee-86f3-3358a59f8c46) the filters used for the mentioned 1st dashboard does not apply as these visualizations targets different metrics like number of release_issues, release_owner assigned (yes/or) etc.

So the solution is:

Embed the dashboards Iframe URL to https://opensearch.org/ similar to what we have to https://opensearch.org/benchmarks. Add all the release dashboards Iframes to this https://opensearch.org/ page so that users can have all the release metrics under on view (in one page). The Iframe embeddings should have the following conditions met.

- [x] Add a navigation page as https://opensearch.org/release-metrics.

- [x] Make sure the Iframe for dashboards part of https://metrics.opensearch.org/_dashboards/app/home is only allowed for https://opensearch.org/, default have the `X-Frame-Options: DENY`. Related PR https://github.com/opensearch-project/opensearch-metrics/pull/70.

- [x] Have a modal view (pop up open and close) in https://opensearch.org/release-metrics for a user to target view of the single dashboard. This is possible with `<h1 onclick=</h1>` with HTML.
      -   <img width="1433" alt="Screenshot 2024-09-03 at 2 52 22 PM" src="https://github.com/user-attachments/assets/ad958753-dcfd-4a09-9a99-d7120c25d1ca" style="margin-bottom: 20px;">

- [x] Have an anchors at the beginning of the page for user to click and go to the target dashboard. This will reduce the scroll for the user and directly viewing the target dashboard. Possible with 
```
<div class="nav-index">
    <a href="#metrics-dashboard">OpenSearch Release Metrics</a>
    <a href="#test-results-dashboard">OpenSearch Release Build and Integration Test Results</a>
</div>
```

 The anchor URL's: 
        * https://opensearch.org/release-metrics#metrics-dashboard
         * https://opensearch.org/release-metrics#test-results-dashboard
        <img width="1311" alt="Screenshot 2024-09-03 at 2 52 47 PM" src="https://github.com/user-attachments/assets/069ac2b4-0dd7-4503-948b-b69d5d8ba65d">

- [x] Along with the dashboards and pop ups have the original dashboard link (https://metrics.opensearch.org/) added to the page so that user can directly go to the main dashboard part of metrics URL.
      <img width="1349" alt="Screenshot 2024-09-03 at 2 57 52 PM" src="https://github.com/user-attachments/assets/98eaa05b-7d04-4086-9f79-be49ce58dff1">

- [x]  Ability for the user to filter the data and visualizations directly from https://opensearch.org/release-metrics. Having this the user should be to get the right data directly under the same view https://opensearch.org/release-metrics. Need not go to https://metrics.opensearch.org/ and click the dashboards again for filtering the data. The idea is not just the single view but also should be able to query the data from https://opensearch.org/release-metrics.
    <img width="1400" alt="Screenshot 2024-09-03 at 2 58 32 PM" src="https://github.com/user-attachments/assets/1c464452-1260-45c1-9c68-2d2c420a5a03">

- [x] The https://opensearch.org/release-metrics should have the share dashboard link of https://metrics.opensearch.org/. Example user added release version query on a dashboard part of https://opensearch.org/release-metrics, now user should have the share button enabled that can copy the directl URL of https://metrics.opensearch.org/ and share it as required. This will allow users to directly add filters to the dashboards and get the exact sharable URL of https://metrics.opensearch.org/ from https://opensearch.org/release-metrics.
     <img width="1330" alt="Screenshot 2024-09-03 at 2 59 00 PM" src="https://github.com/user-attachments/assets/7c337e4a-e3cf-40a5-964a-129d63739101">

### Do you have any additional context?
For the goals to achieve need to make some changes in https://github.com/opensearch-project/project-website/. 
* Related PR https://github.com/opensearch-project/project-website/pull/3254.

**Comment by prudhvigodithi** [comment]
Adding @getsaurabh02 @dblock

**Comment by getsaurabh02** [comment]
Thanks @prudhvigodithi, are there any mocks you would want to share as well?

**Comment by prudhvigodithi** [comment]
Sure Let me share some sample mocks here. Thanks

**Comment by prudhvigodithi** [comment]
Coming from the above requirement:

Make sure the Iframe for dashboards part of https://metrics.opensearch.org/_dashboards/app/home is only allowed for https://opensearch.org/, default have the X-Frame-Options: DENY.

We can use the following to ensure the Iframe is only allowed for https://opensearch.org, we cam update [opensearchNginxProxyReadonly.ts](https://github.com/opensearch-project/opensearch-metrics/blob/main/infrastructure/lib/stacks/opensearchNginxProxyReadonly.ts) accordingly.
```
X-Frame-Options: DENY
add_header Content-Security-Policy "frame-ancestors https://opensearch.org";
```

**Comment by prudhvigodithi** [comment]
Hey I havent seen any mock framework added to the project-website, hence captured a small video on the behaviour based on the issue description. @getsaurabh02 @dblock to please take a look.
https://github.com/user-attachments/assets/1fb5f418-861e-4f9e-af5b-2448c2d24526

**Comment by prudhvigodithi** [comment]
The central view of the release dashboard is now part of the OpenSearch website https://opensearch.org/release-dashboard. Closing this issue.
Thanks
